name: Pull Request Run Test

# Made partially using guide: https://www.youtube.com/watch?v=dHuksXTLA2k

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the codebase
      - name: Checkout code
        uses: actions/checkout@v4

      # Run check script
      - name: Run validation script
        run: |
          bash scripts/testScript/test.sh
          # bash scripts/testScript/check.sh

      # Reject or allow based on exit status
      - name: Set PR Status
        if: failure()
        run: |
          echo "Check.sh failed. Rejecting PR."
          exit 1

      - name: Allow PR
        if: success()
        run: |
          echo "Check.sh passed. Allowing PR."
          exit 0
