---
name: Run test using container
on:
  push:
    branches:
      - test/maccGradedCase
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
jobs:
  run-tests:
    name: Run AutoIG Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/conjure-cp/conjure:main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run container and execute script
        run: >

          apt-get update

          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            bash \
            sudo \
            wget \
            curl \
            gnupg \
            software-properties-common \
            unzip

          # Installing Python Dependencies

          sudo apt-get install -y python3-pip

          apt install python3-pandas -y

          apt install python3-numpy -y

          sudo apt install python-is-python3


          sudo apt-get install r-base -y


          sudo apt-get install git-all -y



          # Getting current branch

          CURRENT_BRANCH="${{ github.ref_name }}"


          git clone -b "$CURRENT_BRANCH" https://github.com/vincepick/AutoIG.git   

          bash bin/install-savilerow.sh 

          bash bin/install-mininzinc.sh

          bash bin/install-runsolver.sh


          bash bin/install-irace.sh 

          bash bin/install-ortools.sh


          bash bin/install-yuck.sh

          bash bin/install-picat.sh

          ls 


          echo "Environment made :D, path:"

          echo $PATH
      - name: Run Push Tests
        if: ${{ github.event_name == 'push' }}
        run: |
          cd AutoIG
          . bin/set-path.sh
          AUTOIG=$(pwd)
          cd $AUTOIG/scripts/testScripts
          echo "Running basic tests for Push"
          bash check_push.sh
      - name: Run Conjure Tests
        if: ${{ github.event_name == 'push' }}
        run: |
          cd AutoIG
          . bin/set-path.sh
          AUTOIG=$(pwd)
          cd $AUTOIG/scripts/testScripts
          echo "Running basic tests for Conjure Usage"
          bash check_conjure.sh
      - name: Run Pull Request Tests
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cd AutoIG
          . bin/set-path.sh
          AUTOIG=$(pwd)
          cd $AUTOIG/scripts/testScripts
          echo "Running more thorough tests for Pull Request"
          bash check_push.sh       
          bash check_pr.sh
      - name: Fail
        if: ${{ failure() }}
        run: |
          echo "These tests failed, rejecting PR."
          exit 1
      - name: Pass
        if: ${{ success() }}
        run: |
          echo "These tests passed! allowing PR."
          exit 0
