name: Run test using container

on:
  push:
    branches:
      - test/maccGradedCase

jobs:
  run-tests:
    name: Run container and execute script
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # build container based on local dockerfile
      - name: Build Docker image
        run: |
          docker build -t autoig-image:latest ${{ github.workspace }}

      # try to container with volume
      # binding to root directory
      - name: Run container and execute script
        run: |
          docker run --rm \ 
            --volume ${{ github.workspace }}:/AutoIG \  
            autoig-image:latest \
            bash -c "
            cd /AutoIG/scripts &&
            . bin/set-path.sh &&
            AUTOIG=\$(pwd) &&
            ./check.sh"

      # if script fails reject PR
      - name: Fail
        if: ${{ failure() }}
        run: |
          echo "Check.sh failed, rejecting PR."
          exit 1

      # if script passes approve PR
      - name: Pass
        if: ${{ success() }}
        run: |
          echo "Check.sh passed, allowing PR."
          exit 0
