name: Run test using container

on:
  push:
    branches:
      - test/maccGradedCase

jobs:
  run-tests:
    name: Run AutoIG Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/conjure-cp/conjure@sha256:ebff76918718631f099544eed3a808cd16ce8f2c863c8229c7d2e417ba745c56
    steps:
      # Checkout repo: checks out current repo (so AutoIG)
      - name: Checkout code
        uses: actions/checkout@v4

      # try to container with volume
      # binding to root directory
      - name: Run container and execute script
        run: |
          echo "Running inside docker container!"
          conjure --version

      # if script fails reject PR
      - name: Fail
        if: ${{ failure() }}
        run: |
          echo "This usecontainer failed, rejecting PR."
          exit 1

      # if script passes approve PR
      - name: Pass
        if: ${{ success() }}
        run: |
          echo "This usecontainer passed, allowing PR."
          exit 0
