name: Run test using container

on:
  push:
    branches:
      - test/maccGradedCase

jobs:
  run-tests:
    name: Run AutoIG Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      # using the main instead of the previous version for now
      image: ghcr.io/conjure-cp/conjure:main

      #previous version
      #ghcr.io/conjure-cp/conjure@sha256:e959c664d83a08b68a5b31409d56ce82eadf0f0b74f8af1809642b73f652c940

      # Current version of conjure
      # ghcr.io/conjure-cp/conjure@sha256:ebff76918718631f099544eed3a808cd16ce8f2c863c8229c7d2e417ba745c56

    steps:
      # Checkout repo: checks out current repo (so AutoIG)
      - name: Checkout code
        uses: actions/checkout@v4

      # try to container with volume
      # binding to root directory
      # currently clones a specific branch
      - name: Run container and execute script
        run: |

          echo "Running inside docker container!"


          echo "Script: $0"
          echo "Shell: $SHELL"
          ps -p $$

          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            bash \
            sudo \
            wget \
            curl \
            gnupg \
            software-properties-common \
            unzip

          sudo apt-get install -y python3-pip
          apt install python3-pandas -y
          apt install python3-numpy -y
          sudo apt install python-is-python3

          sudo apt-get install r-base -y

          sudo apt-get install git-all -y


          # git clone -b test/maccGradedCase https://github.com/stacs-cp/AutoIG.git

          git clone https://github.com/stacs-cp/AutoIG.git
          bash bin/install-savilerow.sh 
          bash bin/install-mininzinc.sh
          bash bin/install-runsolver.sh

          bash bin/install-irace.sh 
          bash bin/install-ortools.sh

          bash bin/install-yuck.sh
          bash bin/install-picat.sh

          ls 

          echo "Reached this point"

          . bin/set-path.sh

          AUTOIG=$(pwd)

          echo "Environment made :D, path:"
          echo $PATH

      # if script fails reject PR
      - name: Fail
        if: ${{ failure() }}
        run: |
          echo "This useContainer failed, rejecting PR."
          exit 1

      # if script passes approve PR
      - name: Pass
        if: ${{ success() }}
        run: |
          echo "This useContainer passed, allowing PR."
          exit 0
